### PR TITLE
fix(deps): Upgraded devDependencies and peerDependencies to latest version

### PR DESCRIPTION
**Pull request by tchopra91**
I have upgraded devDependencies and peerDependencies of the project to their latest version. Also I have verified that all tests are passing and the project is building successfully. Please approve the changes and release a new version of the library for the community.

### CODE REVIEW

**Comment by tchopra91** [comment]
@alex-okrushko please approve this pull request and release a new version of the library.

**Comment by cjk** [comment]
Looks like this repo is now basically unmaintained :disappointed: 
Perhaps it's time to fork it?

**Comment by cjk** [comment]
@tchopra91 Thanks for getting back. I know it's sometimes hard to find the time.

I suggest you postpone the "other" changes and priortize stability + usability until you find the time to make further improvements.

Thanks again for the useful library and heads up!

**Comment by tchopra91** [comment]
@alex-okrushko could you please release this as a patch release so that the community can continue using this library without the unwanted warnings and 3rd party vulnerability concerns.

**Comment by alex-okrushko** [comment]
@tchopra91 @cjk updated and released 7.0.0

sorry for the delay and thanks for using the lib.

**Pull request closed without merging**
